{% set version = '1.4-4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-microbenchmark
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/microbenchmark_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/microbenchmark/microbenchmark_{{ version }}.tar.gz
  sha256: 2cb1aad6f826f6798fbd89ac2a7839c25508596ab684405c8d28fca8b7e0623b

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: ggplot2, multcomp
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('microbenchmark')"           # [not win]
    - "\"%R%\" -e \"library('microbenchmark')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/joshuaulrich/microbenchmark/
  license: BSD_2_clause + file LICENSE
  summary: Provides infrastructure to accurately measure and compare the execution time of R
    expressions.
  license_family: BSD

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: microbenchmark
# Title: Accurate Timing Functions
# Description: Provides infrastructure to accurately measure and compare the execution time of R expressions.
# Authors@R: c(person("Olaf", "Mersmann", role=c("aut")), person("Claudia", "Beleites", role=c("ctb")), person("Rainer", "Hurling", role=c("ctb")), person("Ari", "Friedman", role=c("ctb")), person(given=c("Joshua","M."), family="Ulrich", role="cre", email="josh.m.ulrich@gmail.com"))
# URL: https://github.com/joshuaulrich/microbenchmark/
# BugReports: https://github.com/joshuaulrich/microbenchmark/issues/
# License: BSD_2_clause + file LICENSE
# Imports: graphics, stats
# Suggests: ggplot2, multcomp
# ByteCompile: yes
# LazyData: yes
# Version: 1.4-4
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2018-01-24 11:34:21 UTC; josh
# Author: Olaf Mersmann [aut], Claudia Beleites [ctb], Rainer Hurling [ctb], Ari Friedman [ctb], Joshua M. Ulrich [cre]
# Maintainer: Joshua M. Ulrich <josh.m.ulrich@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-01-24 12:17:05 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
