travis:
  secure:
    BINSTAR_TOKEN: 2flTJb9V+fePSz82Pvs1GHI69CuKmF8y49AbBhiRqrQN4mXILdHxwlnnWmNfEv212RmiJ7ddYeHEgdSiDb0oduZChgKexFjFoNJcW2pKTYkr+bfrE2PWP8a52kgEJSPrSPF3SM/pKY1mvnM2LZ3s0RYGxcfx+KPT8lL8IHnETmacoAGzeQ3Kkvbu/InQbYyC9FYrWhtEFpUW06VUhlqymEHjecy1uQyz+jBFQgsT5vyMFjDsd3+dw92bNWZUfLDt1iAt9XlpobuMLQxoky3LrHkb1YbtMApKwjyYET2u7BqcQePdzAtlacYnABg399TgYf+eFtAvmSm8e1EfRIFQTYiRgMu/0I1FdvbWZqKCg3adZ1Qz4BKHWeXLycP/YBzmv/mmqtPcs7SIZkwGeCLZCdbgtg9vn0MsIBJNg9J4Zzv9ECqrtSY1giHLyJkdfVCQYqEkAhyI9r0Gsb+lDa9h0zEoWJPjCE9etKgCWBgfo0gIfRzc1P9SWotlWshbuHhC9XUyx7bdc8sja7EIwCT6SN4geSenON1SRWJWukNJEEoBP/vMXpodvEozV5UD8ATMeLsR3Apz044UJwV0GGJ2avWHEviJKajZ6niHUqAYnrtGA0XsNT4i9+I+hMKL+YceTkYXmjLiF9xSHBM5lNI1+kqcreq9fI8CNOmQTNo6bIw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
