travis:
  secure:
    BINSTAR_TOKEN: 26PDPngteWOWi/LyGG5wkvbdox6S35Td6YK/i20zCQHEFZ3mSCr5ymFDMLtdhNrRkweKRyKPJC9kY+CmHGJG6pohSu3aOSZ2m4CFzMRKIWgPo8cHTWFUGvGIOpnP+EJlYVRJ3znBZxkwZWBNLQebqKs60gs5LTO7+CF+xI52rAP9NowQl+NCdhHfoYYBOii4Xqg3roldv73olGszuv/r4HAz2bYXebm3sp+0TZQxbjhl72Xvkr+xwhwU0O1+wyJ5dth0nBst0lEQ6pX6w07WGP5KSt4gnfy2KCS0g+B7loB9sZhitXu+ACAwT0x1CrRHv8aGbkRi4IObCvaiXmsRPF49GMhuT3kZEPbciaOrmyXs20emT8gfcqTCIQAldgrEQfRlmr9tp5m0Ni/V/S73MKMt7Zsxho4J3UxVpsgxdAGqUPdJvC76NMcUFPWbpwWiGGWgplufbdEoGgbei6JwUie1ARXjuHAyq6PCewJK63SJjxLtKsi9Itn88vbILFK1MOyt4NtygEaYMF/wd5YZbgr8bhpVVuM0Et8mx8zDrKm7tNGV0COG6YWzSrBMCcdOtO9lqwnO9PjG70UisY0g0758Pi7k2AlS8tXhXvgpbhNUNzapTwJtxSNhs5TDaZi/FAZJHCEOd+tjPvbtlsGvVsySYETe2cmuGtzuzJ5Nv4U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
